### ISSUE TITLE
Serialport issue

### ISSUE THREAD

**Issue by minzukas** [fpv-wtf/margerine#30]
Get this message on Ubuntu

margerine-master$ node margerine.js unlock
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'serialport'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mindaugas/Downloads/margerine-master(1)/margerine-master/margerine.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by minzukas** [comment]
installing serialport now gives:

$ node margerine.js unlock
/home/mindaugas/Downloads/margerine-master(1)/margerine-master/node_modules/yargs-parser/build/index.cjs:1013
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/home/mindaugas/Downloads/margerine-master(1)/margerine-master/node_modules/yargs-parser/build/index.cjs:1013:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mindaugas/Downloads/margerine-master(1)/margerine-master/node_modules/yargs/build/index.cjs:1:58028)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

**Comment by j005u** [comment]
Sorry for the delayed response.

Like the readme says, margerine doesn't work properly on Linux. Use https://testing.fpv.wtf/ instead.
